# Generated by Django 5.2.7 on 2025-10-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_agregada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
