# Generated by Django 5.2.7 on 2025-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_fecha_agregada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='actualizada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
