# Generated by Django 5.2.7 on 2025-11-26 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_pelicula_actualizada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('participantes', models.ManyToManyField(related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='peliculas.conversacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje', 'Nuevo Mensaje'), ('watch_party', 'Invitación a Watch Party'), ('resena', 'Nueva Reseña'), ('sistema', 'Notificación del Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado_terminos', models.BooleanField(default=False)),
                ('fecha_aceptacion_terminos', models.DateTimeField(blank=True, null=True)),
                ('version_terminos', models.CharField(default='1.0', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='WatchParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='esperando', max_length=20)),
                ('tiempo_actual', models.IntegerField(default=0, help_text='Segundo actual del video')),
                ('esta_reproduciendo', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('publico', models.BooleanField(default=False, help_text='Si es público, cualquiera puede unirse')),
                ('max_participantes', models.IntegerField(default=10)),
                ('codigo_invitacion', models.CharField(blank=True, max_length=20, unique=True)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_parties_creadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='watch_parties_participando', to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_parties', to='peliculas.pelicula')),
            ],
            options={
                'verbose_name': 'Watch Party',
                'verbose_name_plural': 'Watch Parties',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWatchParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='peliculas.watchparty')),
            ],
            options={
                'verbose_name': 'Mensaje de Watch Party',
                'verbose_name_plural': 'Mensajes de Watch Party',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('duracion_vista', models.IntegerField(default=0, help_text='Minutos vistos')),
                ('completada', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Visualización',
                'verbose_name_plural': 'Historiales de Visualización',
                'ordering': ['-fecha_visualizacion'],
                'unique_together': {('usuario', 'pelicula', 'fecha_visualizacion')},
            },
        ),
    ]
