# Generated by Django 5.2.7 on 2025-11-27 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_conversacion_mensaje_notificacion_perfilusuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='util_count',
        ),
        migrations.AddField(
            model_name='resena',
            name='usuarios_util',
            field=models.ManyToManyField(blank=True, related_name='resenas_utiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
