# Generated by Django 5.2.7 on 2025-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_remove_resena_util_count_resena_usuarios_util'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='usuarios_util',
        ),
        migrations.AddField(
            model_name='resena',
            name='util_count',
            field=models.IntegerField(default=0, help_text='Votos de utilidad'),
        ),
    ]
